=====================================================
Start Time  : Sat Jul  1 18:51:50 EDT 2023
Submit Dir  : /projects/raw_lab/jobs/metacerberus
Job ID/Name : 4129662 / Metacerberus
Node List   : str-c99
Num Tasks   : 1 total [1 nodes @ 16 CPUs/node]
======================================================

======================================================
Running Metacerberus On VIRAL_ARCHAEA/GCA_001441135.1.fna
======================================================
HMM: 'KOFam_all'
HMM: 'COG'
HMM: 'VOG'
HMM: 'PHROG'
HMM: 'CAZy'

Starting MetaCerberus Pipeline

Checking for external dependencies:
fastqc               /users/jlfiguer/.conda/envs/metacerberus-dev/bin/fastqc
flash2               /users/jlfiguer/.conda/envs/metacerberus-dev/bin/flash2
fastp                /users/jlfiguer/.conda/envs/metacerberus-dev/bin/fastp
porechop             /users/jlfiguer/.conda/envs/metacerberus-dev/bin/porechop
bbduk.sh             /users/jlfiguer/.conda/envs/metacerberus-dev/bin/bbduk.sh
FragGeneScanRs       /users/jlfiguer/.conda/envs/metacerberus-dev/lib/python3.10/site-packages/meta_cerberus/FGS/FragGeneScanRs
prodigal             /users/jlfiguer/.conda/envs/metacerberus-dev/bin/prodigal
hmmsearch            /users/jlfiguer/.conda/envs/metacerberus-dev/bin/hmmsearch
countAssembly.py     /users/jlfiguer/.conda/envs/metacerberus-dev/bin/countAssembly.py
Initializing RAY
2023-07-01 18:51:54,214	INFO worker.py:1627 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
Started RAY single node
Running RAY on 1 node(s)
Using 16 CPUs per node

STEP 1: Loading sequence files:
Processing 0 fastq sequences
Processing 1 fasta sequences
Processing 0 protein Sequences

STEP 5a: Removing N's from contig files

STEP 6: Metaome Stats

Command '['/users/jlfiguer/.conda/envs/metacerberus-dev/bin/countAssembly.py', '-f', '/projects/raw_lab/jobs/metacerberus/VIRAL_ARCHAEA/GCA_001441135.1.fna', '-i 100']' returned non-zero exit status 1.
Error: countAssembly.py failed: step_06-metaomeQC/prodigal_GCA_001441135.1
['/users/jlfiguer/.conda/envs/metacerberus-dev/bin/countAssembly.py', '-f', '/projects/raw_lab/jobs/metacerberus/VIRAL_ARCHAEA/GCA_001441135.1.fna', '-i 100']
Traceback (most recent call last):
  File "/users/jlfiguer/.conda/envs/metacerberus-dev/bin/metacerberus.py", line 684, in <module>
    sys.exit(main())
  File "/users/jlfiguer/.conda/envs/metacerberus-dev/bin/metacerberus.py", line 441, in main
    readStats[key] = metacerberus_metastats.getReadStats(value[0], config, os.path.join(STEP[6], key))
  File "/users/jlfiguer/.conda/envs/metacerberus-dev/lib/python3.10/site-packages/meta_cerberus/metacerberus_metastats.py", line 28, in getReadStats
    return stats
UnboundLocalError: local variable 'stats' referenced before assignment
Command exited with non-zero status 1
3.79user 1.20system 0:07.77elapsed 64%CPU (0avgtext+0avgdata 219844maxresident)k
0inputs+704outputs (0major+112517minor)pagefaults 0swaps

======================================================
End Time   : Sat Jul  1 18:51:58 EDT 2023
Run Time   : 8 seconds
======================================================

